### ISSUE TITLE
A BUG This plug-in is not available at 1.14.4

### ISSUE THREAD

**Issue by FxRayHughes** [mastercake10/CustomOreGen#21]
[08:18:06] [Server thread/ERROR]: Could not pass event BlockFromToEvent to CustomOreGen v1.3.16-SNAPSHOT
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot-1.14.4.jar:git-Spigot-1981d55-c88867e]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.14.4.jar:git-Spigot-1981d55-c88867e]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529) ~[spigot-1.14.4.jar:git-Spigot-1981d55-c88867e]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514) ~[spigot-1.14.4.jar:git-Spigot-1981d55-c88867e]
        at net.minecraft.server.v1_14_R1.FluidTypeFlowing.a(FluidTypeFlowing.java:187) ~[spigot-1.14.4.jar:git-Spigot-1981d55-c88867e]
        at net.minecraft.server.v1_14_R1.FluidTypeFlowing.a(FluidTypeFlowing.java:159) ~[spigot-1.14.4.jar:git-Spigot-1981d55-c88867e]
        at net.minecraft.server.v1_14_R1.FluidTypeFlowing.a(FluidTypeFlowing.java:493) ~[spigot-1.14.4.jar:git-Spigot-1981d55-c88867e]
        at net.minecraft.server.v1_14_R1.Fluid.a(SourceFile:70) ~[spigot-1.14.4.jar:git-Spigot-1981d55-c88867e]
        at net.minecraft.server.v1_14_R1.WorldServer.a(WorldServer.java:533) ~[spigot-1.14.4.jar:git-Spigot-1981d55-c88867e]
        at net.minecraft.server.v1_14_R1.TickListServer.b(TickListServer.java:82) [spigot-1.14.4.jar:git-Spigot-1981d55-c88867e]
        at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:264) [spigot-1.14.4.jar:git-Spigot-1981d55-c88867e]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1067) [spigot-1.14.4.jar:git-Spigot-1981d55-c88867e]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:396) [spigot-1.14.4.jar:git-Spigot-1981d55-c88867e]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:969) [spigot-1.14.4.jar:git-Spigot-1981d55-c88867e]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:814) [spigot-1.14.4.jar:git-Spigot-1981d55-c88867e]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
Caused by: java.lang.NullPointerException
        at xyz.spaceio.hooks.HookuSkyBlock.getIslandOwner(HookuSkyBlock.java:28) ~[?:?]
        at xyz.spaceio.customoregen.CustomOreGen.getOwner(CustomOreGen.java:176) ~[?:?]
        at xyz.spaceio.customoregen.Events.onFromTo(Events.java:51) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_101]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot-1.14.4.jar:git-Spigot-1981d55-c88867e]
        ... 15 more

**Comment by mastercake10** [comment]
Can you provide some background information, please?

**Comment by antiburen** [comment]
I'm using PaperMC 1.14.4

when you break a block and CustomOreGen try to generate it randomly, it say in console:

[17:01:26 ERROR]: Could not pass event BlockFromToEvent to CustomOreGen v1.3.16-SNAPSHOT
java.lang.NullPointerException: null
        at java.util.Objects.requireNonNull(Objects.java:203) ~[?:1.8.0_222]
        at java.util.Optional.<init>(Optional.java:96) ~[?:1.8.0_222]
        at java.util.Optional.of(Optional.java:108) ~[?:1.8.0_222]
        at xyz.spaceio.hooks.HookIslandWorld.getIslandOwner(HookIslandWorld.java:32) ~[?:?]
        at xyz.spaceio.customoregen.CustomOreGen.getOwner(CustomOreGen.java:176) ~[?:?]
        at xyz.spaceio.customoregen.Events.onFromTo(Events.java:51) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor484.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-149]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-149]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-149]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-149]
        at net.minecraft.server.v1_14_R1.FluidTypeFlowing.a(FluidTypeFlowing.java:188) ~[patched_1.14.4.jar:git-Paper-149]
        at net.minecraft.server.v1_14_R1.FluidTypeFlowing.a(FluidTypeFlowing.java:159) ~[patched_1.14.4.jar:git-Paper-149]
        at net.minecraft.server.v1_14_R1.FluidTypeFlowing.a(FluidTypeFlowing.java:508) ~[patched_1.14.4.jar:git-Paper-149]
        at net.minecraft.server.v1_14_R1.Fluid.a(SourceFile:70) ~[patched_1.14.4.jar:git-Paper-149]
        at net.minecraft.server.v1_14_R1.WorldServer.a(WorldServer.java:549) ~[patched_1.14.4.jar:git-Paper-149]
        at net.minecraft.server.v1_14_R1.TickListServer.b(TickListServer.java:90) ~[patched_1.14.4.jar:git-Paper-149]
        at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:273) ~[patched_1.14.4.jar:git-Paper-149]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1207) ~[patched_1.14.4.jar:git-Paper-149]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:420) ~[patched_1.14.4.jar:git-Paper-149]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1074) ~[patched_1.14.4.jar:git-Paper-149]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:918) ~[patched_1.14.4.jar:git-Paper-149]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]





Please if you need more info ask me and I will give it.

**Comment by mastercake10** [comment]
Which skyblock plugin (and version) are you using in your issue?

**Comment by antiburen** [comment]
IslandWorld 1.14

https://www.spigotmc.org/resources/island-world-%E2%9A%A1-1-14-support-%E2%9A%A1-best-skyblock-plugin-%E2%9A%A1.63803/update?update=289424

**Comment by mastercake10** [comment]
This plugin is not supported by COG, only this one: https://www.spigotmc.org/resources/island-world-skyblock-replacement.2757/
