### ISSUE TITLE
doesnt start on 1.8

### ISSUE THREAD

**Issue by Haeherfeder** [mastercake10/CustomOreGen#30]
weiter plugins: Essentials, essentials spawn

[23:29:06] [Server thread/ERROR]: Could not load 'plugins/CustomOreGen.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: xyz/spaceio/customoregen/CustomOreGen : Unsupported major.minor version 52.0
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[minecraft_server.jar:git-Spigot-8a983f9-e81edfc]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[minecraft_server.jar:git-Spigot-8a983f9-e81edfc]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [minecraft_server.jar:git-Spigot-8a983f9-e81edfc]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugins(CraftServer.java:291) [minecraft_server.jar:git-Spigot-8a983f9-e81edfc]
	at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:152) [minecraft_server.jar:git-Spigot-8a983f9-e81edfc]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:505) [minecraft_server.jar:git-Spigot-8a983f9-e81edfc]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_80]
Caused by: java.lang.UnsupportedClassVersionError: xyz/spaceio/customoregen/CustomOreGen : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.7.0_80]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800) ~[?:1.7.0_80]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.7.0_80]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449) ~[?:1.7.0_80]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71) ~[?:1.7.0_80]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361) ~[?:1.7.0_80]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355) ~[?:1.7.0_80]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_80]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354) ~[?:1.7.0_80]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[minecraft_server.jar:git-Spigot-8a983f9-e81edfc]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[minecraft_server.jar:git-Spigot-8a983f9-e81edfc]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_80]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_80]
	at java.lang.Class.forName0(Native Method) ~[?:1.7.0_80]
	at java.lang.Class.forName(Class.java:278) ~[?:1.7.0_80]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[minecraft_server.jar:git-Spigot-8a983f9-e81edfc]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[minecraft_server.jar:git-Spigot-8a983f9-e81edfc]
	... 6 more

**Comment by MattTek** [comment]
You need to update to Java 8

**Comment by Haeherfeder** [comment]
> You need to update to Java 8

this is not possible by nitrado, or?

**Comment by tyler489** [comment]
You would have to contact them as the plugin requires java 8.
