### ISSUE TITLE
PlotSquared 1.14 issue

### ISSUE THREAD

**Issue by mastercake10** [mastercake10/CustomOreGen#34]
### What steps will reproduce the issue?  
1. Install the newest [PlotSquared](https://github.com/IntellectualSites/PlotSquared) version
2. Setup a generator
3. Break a block 

### What was supposed to happen?
Ore generation

### What happened instead? 
Stacktrace in console

### What version of this plugin are you using?  
Latest

### What Spigot version are you using? Paste the output of /version below.  
1.14.4

### What plugins do you have installed? Paste the output of /plugins below.  
-

### Are any errors related to this plugin in your console or logs? If so, paste below.  
```
[Server thread/ERROR]: Could not pass event BlockFromToEvent to AdvancedOreGen v1.6.25-SNAPSHOT
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot.jar:git-Spigot-94af569-a3fdef8]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot.jar:git-Spigot-94af569-a3fdef8]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529) ~[spigot.jar:git-Spigot-94af569-a3fdef8]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514) ~[spigot.jar:git-Spigot-94af569-a3fdef8]
        at net.minecraft.server.v1_14_R1.FluidTypeFlowing.a(FluidTypeFlowing.java:187) ~[spigot.jar:git-Spigot-94af569-a3fdef8]
        at net.minecraft.server.v1_14_R1.FluidTypeFlowing.a(FluidTypeFlowing.java:159) ~[spigot.jar:git-Spigot-94af569-a3fdef8]
        at net.minecraft.server.v1_14_R1.FluidTypeFlowing.a(FluidTypeFlowing.java:493) ~[spigot.jar:git-Spigot-94af569-a3fdef8]
        at net.minecraft.server.v1_14_R1.Fluid.a(SourceFile:70) ~[spigot.jar:git-Spigot-94af569-a3fdef8]
        at net.minecraft.server.v1_14_R1.WorldServer.a(WorldServer.java:533) ~[spigot.jar:git-Spigot-94af569-a3fdef8]
        at net.minecraft.server.v1_14_R1.TickListServer.b(TickListServer.java:82) [spigot.jar:git-Spigot-94af569-a3fdef8]
        at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:264) [spigot.jar:git-Spigot-94af569-a3fdef8]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1068) [spigot.jar:git-Spigot-94af569-a3fdef8]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:393) [spigot.jar:git-Spigot-94af569-a3fdef8]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:970) [spigot.jar:git-Spigot-94af569-a3fdef8]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:815) [spigot.jar:git-Spigot-94af569-a3fdef8]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
Caused by: java.lang.NoSuchMethodError: com.github.intellectualsites.plotsquared.plot.object.Location: method <init>()V not found
        at xyz.spaceio.hooks.HookPlotSquared.getPSLocation(HookPlotSquared.java:42) ~[?:?]
        at xyz.spaceio.hooks.HookPlotSquared.getIslandOwner(HookPlotSquared.java:29) ~[?:?]
        at xyz.spaceio.AdvancedOreGen.Events.onFromTo(Events.java:115) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_191]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot.jar:git-Spigot-94af569-a3fdef8]
        ... 15 more
```

**Comment by mastercake10** [comment]
fixed in last commit
