### ISSUE TITLE
CutomOreGen does not work when the island owner if offline.

### ISSUE THREAD

**Issue by Rulol4** [mastercake10/CustomOreGen#39]
### What steps will reproduce the issue?  
1. Download and install uSkyblock & CustomOreGen
2. Invite a player to your island
3. Leave the server
4. Let the other player use a cobblestone gen.
### What was supposed to happen?
Ores & Stone should form.
### What happened instead? 
Just normal cobblestone formed.
### What version of this plugin are you using?  
1.3.24
### What Spigot version are you using? Paste the output of /version below.  
This server is running CraftBukkit version git-Spigot-3b314f5-e2790ae (MC: 1.15) (Implementing API version 1.15-R0.1-SNAPSHOT)
### What plugins do you have installed? Paste the output of /plugins below.  
Plugins (9): Elemental_Server_Essentials, WorldEdit, ViaVersion, Vault, Multiverse-Core, WorldGuard, uSkyBlock, Multiverse-NetherPortals, CustomOreGen
### Are any errors related to this plugin in your console or logs? If so, paste below.  
```
[ERROR] Could not pass event BlockFromToEvent to CustomOreGen v1.3.25-SNAPSHOT

org.bukkit.event.EventException: null

at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot-1.15.jar:git-Spigot-3b314f5-e2790ae]

at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.15.jar:git-Spigot-3b314f5-e2790ae]

at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529) ~[spigot-1.15.jar:git-Spigot-3b314f5-e2790ae]

at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514) ~[spigot-1.15.jar:git-Spigot-3b314f5-e2790ae]

at net.minecraft.server.v1_15_R1.FluidTypeFlowing.a(FluidTypeFlowing.java:187) ~[spigot-1.15.jar:git-Spigot-3b314f5-e2790ae]

at net.minecraft.server.v1_15_R1.FluidTypeFlowing.a(FluidTypeFlowing.java:159) ~[spigot-1.15.jar:git-Spigot-3b314f5-e2790ae]

at net.minecraft.server.v1_15_R1.FluidTypeFlowing.a(FluidTypeFlowing.java:493) ~[spigot-1.15.jar:git-Spigot-3b314f5-e2790ae]

at net.minecraft.server.v1_15_R1.Fluid.a(SourceFile:69) ~[spigot-1.15.jar:git-Spigot-3b314f5-e2790ae]

at net.minecraft.server.v1_15_R1.WorldServer.a(WorldServer.java:581) ~[spigot-1.15.jar:git-Spigot-3b314f5-e2790ae]

at net.minecraft.server.v1_15_R1.WorldServer$$Lambda$2861.0000000060EEC0A0.accept(Unknown Source) ~[?:?]

at net.minecraft.server.v1_15_R1.TickListServer.b(TickListServer.java:82) [spigot-1.15.jar:git-Spigot-3b314f5-e2790ae]

at net.minecraft.server.v1_15_R1.WorldServer.doTick(WorldServer.java:304) [spigot-1.15.jar:git-Spigot-3b314f5-e2790ae]

at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1076) [spigot-1.15.jar:git-Spigot-3b314f5-e2790ae]

at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:393) [spigot-1.15.jar:git-Spigot-3b314f5-e2790ae]

at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:978) [spigot-1.15.jar:git-Spigot-3b314f5-e2790ae]

at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:823) [spigot-1.15.jar:git-Spigot-3b314f5-e2790ae]

at java.lang.Thread.run(Thread.java:813) [?:1.8.0_212]

Caused by: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.NullPointerException

at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2217) ~[spigot-1.15.jar:git-Spigot-3b314f5-e2790ae]

at com.google.common.cache.LocalCache.get(LocalCache.java:4154) ~[spigot-1.15.jar:git-Spigot-3b314f5-e2790ae]

at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158) ~[spigot-1.15.jar:git-Spigot-3b314f5-e2790ae]

at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147) ~[spigot-1.15.jar:git-Spigot-3b314f5-e2790ae]

at xyz.spaceio.hooks.SkyblockAPICached.getIslandLevel(SkyblockAPICached.java:48) ~[?:?]

at xyz.spaceio.customoregen.CustomOreGen.getLevel(CustomOreGen.java:179) ~[?:?]

at xyz.spaceio.customoregen.CustomOreGen.getGeneratorConfigForPlayer(CustomOreGen.java:222) ~[?:?]

at xyz.spaceio.customoregen.Events.onFromTo(Events.java:70) ~[?:?]

at sun.reflect.GeneratedMethodAccessor69.invoke(Unknown Source) ~[?:?]

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]

at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]

at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot-1.15.jar:git-Spigot-3b314f5-e2790ae]

... 16 more
```
### Any additional information that you would like to provide that may be relevant to the issue?
This problem only happens when the island owner is offline. 
if the island owner is online everything works just fine.

I don't know if this is a problem whit the CutomOreGen plugin or whit the uSkyblock plugin, but on the spigot page it says that CustomOreGen is compatible whit uSkyblock.

**Comment by MattTek** [comment]
CustomOreGen does not have offline owner support. If you're interested in having offline owner support on your server you can check out MasterCake's other generator plugin [AdvancedOreGen](https://www.spigotmc.org/resources/advancedoregen.40527/)
