### ISSUE TITLE
SuperiorSkyblock2 hook not up to date

### ISSUE THREAD

**Issue by mastercake10** [mastercake10/CustomOreGen#45]
```java
[23:30:08 ERROR]: Could not pass event PlayerJoinEvent to CustomOreGen v1.3.31-SNAPSHOT
java.lang.NoSuchMethodError: 'org.bukkit.World com.bgsoftware.superiorskyblock.api.SuperiorSkyblockAPI.getIslandsWorld()'
        at xyz.spaceio.hooks.HookSuperiorSkyblock.getSkyBlockWorldNames(HookSuperiorSkyblock.java:39) ~[?:?]
        at xyz.spaceio.customoregen.CustomOreGen.getActiveWorlds(CustomOreGen.java:174) ~[?:?]
        at xyz.spaceio.customoregen.CustomOreGen.getGeneratorConfigForPlayer(CustomOreGen.java:245) ~[?:?]
        at xyz.spaceio.customoregen.Events.onJoin(Events.java:147) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor544.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Airplane-12]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.16.5.jar:git-Airplane-12]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Airplane-12]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Airplane-12]
        at net.minecraft.server.v1_16_R3.PlayerList.postChunkLoadJoin(PlayerList.java:357) ~[patched_1.16.5.jar:git-Airplane-12]
        at net.minecraft.server.v1_16_R3.PlayerList.lambda$null$1(PlayerList.java:304) ~[patched_1.16.5.jar:git-Airplane-12]
        at net.minecraft.server.v1_16_R3.PlayerConnection.tick(PlayerConnection.java:316) ~[patched_1.16.5.jar:git-Airplane-12]
        at net.minecraft.server.v1_16_R3.NetworkManager.a(NetworkManager.java:592) ~[patched_1.16.5.jar:git-Airplane-12]
        at net.minecraft.server.v1_16_R3.ServerConnection.c(ServerConnection.java:173) ~[patched_1.16.5.jar:git-Airplane-12]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1587) ~[patched_1.16.5.jar:git-Airplane-12]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.16.5.jar:git-Airplane-12]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1407) ~[patched_1.16.5.jar:git-Airplane-12]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1139) ~[patched_1.16.5.jar:git-Airplane-12]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:292) ~[patched_1.16.5.jar:git-Airplane-12]
        at java.lang.Thread.run(Thread.java:831) [?:?]
```

**Comment by mastercake10** [comment]
fixed in df13624
